# Cloud Build configuration for budget-anomaly-monitor as Cloud Run Job
# This file defines the steps to build and deploy the monitoring job

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/budget-anomaly-monitor:$COMMIT_SHA', 'budget-anomaly-monitor/']
    dir: '.'  # Run from repo root

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/budget-anomaly-monitor:$COMMIT_SHA']

  # Step 3: Deploy as Cloud Run Job (not service)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'replace'  # This will create if doesn't exist, or update if exists
      - 'budget-alert-pipeline'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/budget-anomaly-monitor:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--service-account'
      - 'extract-meta-ads@generative-ai-418805.iam.gserviceaccount.com'
      - '--update-secrets'
      - 'META_BUSINESS_ID=meta-business-id:latest'
      - '--update-secrets'
      - 'META_ACCESS_TOKEN=meta-access-token:latest'
      - '--update-secrets'
      - 'META_APP_SECRET=meta-app-secret:latest'
      - '--update-secrets'
      - 'META_APP_ID=meta-app-id:latest'
      - '--update-secrets'
      - 'GOOGLE_CHAT_WEBHOOK_URL=google-chat-webhook:latest'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--task-timeout'
      - '600'  # 10 minutes per execution
      - '--max-retries'
      - '1'
      - '--parallelism'
      - '1'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/budget-anomaly-monitor:$COMMIT_SHA'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY